### ISSUE TITLE
WSL2 docker container fails to start

### ISSUE THREAD

**Issue by dp770** [aws-deepracer-community/deepracer-sagemaker-container#6]
Hi,

I'm trying to run WSL2-based docker container for "deepracer-sagemaker:4.0.0-gpu" image. Container fails to start up due to missing "resourceconfig.json" file. I can see that this file is used later to derive host name and replace it in "changehostname.c" file, which in case of failure becomes malformed.

`
    CURRENT_HOST=$(jq .current_host  /opt/ml/input/config/resourceconfig.json)
    sed -ie "s/PLACEHOLDER_HOSTNAME/$CURRENT_HOST/g" /changehostname.c
`

Container fails to start up:

> jq: error: Could not open file /opt/ml/input/config/resourceconfig.json: No such file or directory
> 
> /changehostname.c: In function 'gethostname':
> 
> /changehostname.c:15:21: error: expected expression before ';' token
> 
> const char *val = ;
> 
> ^
> 
> gcc: error: /changehostname.o: No such file or directory
> 
> ERROR: ld.so: object '/libchangehostname.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

I would appreciated any direction or idea how to fix this.

Thank you

**Comment by WenchaoLin** [comment]
@dp770 same error.  Have you solved it?
